export enum Messages {
  OBJECT_ADDED = "OBJECT_ADDED",
  OBJECT_REMOVED = "OBJECT_REMOVED",
  ANY = "ANY",
  STATE_CHANGED = "STATE_CHANGED",
  COMPONENT_ADDED = "COMPONENT_ADDED",
  COMPONENT_REMOVED = "COMPONENT_REMOVED"
}

export enum Attributes {
  DYNAMICS = "DYNAMICS"
}
